
import javax.swing.JLabel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Justin
 */
public class CookieTracker extends javax.swing.JFrame {
    CookieSales girlScout = new CookieSales();
    /**
     * Creates new form NewJFrame
     */
    public CookieTracker() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ThinMint_button = new javax.swing.JButton();
        Samoa_Button = new javax.swing.JButton();
        ChocoChip_button = new javax.swing.JButton();
        All_button = new javax.swing.JButton();
        lblTM = new javax.swing.JLabel();
        lblSM = new javax.swing.JLabel();
        lblCC = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblTM_total = new javax.swing.JLabel();
        lblSM_total = new javax.swing.JLabel();
        lblCC_total = new javax.swing.JLabel();
        lblTotal_total = new javax.swing.JLabel();
        lblHeader = new javax.swing.JLabel();
        Finalize_button = new javax.swing.JButton();
        lblAll_total = new javax.swing.JLabel();
        CustomTotalField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ThinMint_button.setText("Thin Mint");
        ThinMint_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThinMint_buttonActionPerformed(evt);
            }
        });

        Samoa_Button.setText("Samoa");
        Samoa_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Samoa_ButtonActionPerformed(evt);
            }
        });

        ChocoChip_button.setText("Chocolate Chip");
        ChocoChip_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChocoChip_buttonActionPerformed(evt);
            }
        });

        All_button.setText("Give me one of each!");
        All_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                All_buttonActionPerformed(evt);
            }
        });

        lblTM.setText("Thin Mints: ");

        lblSM.setText("Samoas:");

        lblCC.setText("Chocolate Chip:");

        lblTotal.setText("Total:");

        lblTM_total.setText("0");

        lblSM_total.setText("0");

        lblCC_total.setText("0");

        lblTotal_total.setText("$0");

        lblHeader.setText("Welcome to the Girl Scout Cookie Tracker Thingy!");

        Finalize_button.setText("Finalize order!");
        Finalize_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Finalize_buttonActionPerformed(evt);
            }
        });

        lblAll_total.setText("$0");

        CustomTotalField.setText("0");
        CustomTotalField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomTotalFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(Finalize_button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(lblAll_total, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(All_button)
                            .addComponent(CustomTotalField, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ThinMint_button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Samoa_Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ChocoChip_button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblCC)
                                    .addComponent(lblTotal)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSM, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblTM, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTM_total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSM_total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCC_total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTotal_total, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))))
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CustomTotalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ThinMint_button)
                    .addComponent(lblTM)
                    .addComponent(lblTM_total))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Samoa_Button)
                    .addComponent(lblSM)
                    .addComponent(lblSM_total))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChocoChip_button)
                    .addComponent(lblCC)
                    .addComponent(lblCC_total))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(All_button)
                    .addComponent(lblTotal)
                    .addComponent(lblTotal_total))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Finalize_button)
                    .addComponent(lblAll_total))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CustomTotalFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomTotalFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustomTotalFieldActionPerformed

    private void ThinMint_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThinMint_buttonActionPerformed
        int p = getCustom();
        for (int i = 0; i < p; i++)
            girlScout.addTM();
        updateCookie(lblTM_total, girlScout.getTMCount());
        updateTotal();
    }//GEN-LAST:event_ThinMint_buttonActionPerformed

    private void Samoa_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Samoa_ButtonActionPerformed
        int p = getCustom();
        for (int i = 0; i < p; i++)
            girlScout.addSM();
        updateCookie(lblSM_total, girlScout.getSMCount());
        updateTotal();
    }//GEN-LAST:event_Samoa_ButtonActionPerformed

    private void ChocoChip_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChocoChip_buttonActionPerformed
        int p = getCustom();
        for (int i = 0; i < p; i++)
            girlScout.addCC();
        updateCookie(lblCC_total, girlScout.getCCCount());
        updateTotal();
    }//GEN-LAST:event_ChocoChip_buttonActionPerformed

    private void All_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_All_buttonActionPerformed
        int p = getCustom();
        for (int i = 0; i < p; i++){
            girlScout.addCC();
            girlScout.addSM();
            girlScout.addTM();
        }
        updateALLCookies();
        updateTotal();
    }//GEN-LAST:event_All_buttonActionPerformed

    private void Finalize_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Finalize_buttonActionPerformed
        lblAll_total.setText(String.format("$%d", girlScout.getTotalSales()));
        girlScout.resetOrder();
        updateALLCookies();
        updateTotal();
    }//GEN-LAST:event_Finalize_buttonActionPerformed
    private void updateCookie(JLabel label, int total){
        label.setText(String.format("%d", total));
    }
    private void updateTotal(){
        lblTotal_total.setText(String.format("$%d", girlScout.getTotalSales()));
    }
    private void updateALLCookies(){
        updateCookie(lblTM_total, girlScout.getTMCount());
        updateCookie(lblSM_total, girlScout.getSMCount());
        updateCookie(lblCC_total, girlScout.getCCCount());
    }
    
    private int getCustom(){
        int p = Integer.parseInt(CustomTotalField.getText());
        CustomTotalField.setText("0");
        if (p != 0){
            return p;
        }
        else{
            return 1;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CookieTracker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CookieTracker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CookieTracker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CookieTracker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CookieTracker().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton All_button;
    private javax.swing.JButton ChocoChip_button;
    private javax.swing.JTextField CustomTotalField;
    private javax.swing.JButton Finalize_button;
    private javax.swing.JButton Samoa_Button;
    private javax.swing.JButton ThinMint_button;
    private javax.swing.JLabel lblAll_total;
    private javax.swing.JLabel lblCC;
    private javax.swing.JLabel lblCC_total;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblSM;
    private javax.swing.JLabel lblSM_total;
    private javax.swing.JLabel lblTM;
    private javax.swing.JLabel lblTM_total;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotal_total;
    // End of variables declaration//GEN-END:variables
}
