/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author Justin
 */
public class RestaurantGUI extends javax.swing.JFrame {
    ArrayList<String> _rListNames = new ArrayList();
    Restaurant curr_restaurant = new Restaurant();
    File file = new File("C:\\Users\\Justin\\Documents\\GitHub\\CS372\\PR4_1\\RestaurantNames\\Names.txt");
    /**
     * Creates new form RestaurantGUI
     */
    public RestaurantGUI() {
        initComponents();
        try{
            BufferedReader in = new BufferedReader(new FileReader(file));
            String name;
            while ((name = in.readLine())!= null){
                ((DefaultListModel)listR.getModel()).addElement(name);
            }
            
            in.close();
        }
        catch(Exception e){System.out.println("Code better");}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogR = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtLocation = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        rate1 = new javax.swing.JRadioButton();
        rate2 = new javax.swing.JRadioButton();
        rate3 = new javax.swing.JRadioButton();
        rate4 = new javax.swing.JRadioButton();
        rate5 = new javax.swing.JRadioButton();
        buttonAddR = new javax.swing.JButton();
        buttonCancelR = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        listR = new javax.swing.JList();
        lblHeader = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtD = new javax.swing.JTextArea();
        buttonAdd = new javax.swing.JButton();
        buttonEdit = new javax.swing.JButton();

        dialogR.setBounds(new java.awt.Rectangle(150, 150, 460, 450));

        jLabel1.setText("Name:");

        jLabel2.setText("Location:");

        jLabel3.setText("Rating:");

        jLabel4.setText("Description:");

        txtDescription.setColumns(20);
        txtDescription.setRows(5);
        jScrollPane3.setViewportView(txtDescription);

        buttonGroup1.add(rate1);
        rate1.setText("1");
        rate1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rate1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        rate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rate1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rate2);
        rate2.setText("2");
        rate2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rate2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        rate2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rate2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rate3);
        rate3.setText("3");
        rate3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rate3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        rate3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rate3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rate4);
        rate4.setText("4");
        rate4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rate4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        rate4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rate4ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rate5);
        rate5.setText("5");
        rate5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rate5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        rate5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rate5ActionPerformed(evt);
            }
        });

        buttonAddR.setText("Accept");
        buttonAddR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddRActionPerformed(evt);
            }
        });

        buttonCancelR.setText("Cancel");
        buttonCancelR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogRLayout = new javax.swing.GroupLayout(dialogR.getContentPane());
        dialogR.getContentPane().setLayout(dialogRLayout);
        dialogRLayout.setHorizontalGroup(
            dialogRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogRLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(dialogRLayout.createSequentialGroup()
                        .addGroup(dialogRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(dialogRLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rate1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rate2)))
                        .addGap(1, 1, 1)
                        .addComponent(rate3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rate4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rate5)
                        .addGap(0, 277, Short.MAX_VALUE))
                    .addGroup(dialogRLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLocation))
                    .addGroup(dialogRLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtName))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogRLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonCancelR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonAddR)
                        .addGap(19, 19, 19)))
                .addContainerGap())
        );
        dialogRLayout.setVerticalGroup(
            dialogRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogRLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(dialogRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(dialogRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(dialogRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(rate1)
                        .addComponent(rate3)
                        .addComponent(rate4)
                        .addComponent(rate5))
                    .addComponent(rate2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(dialogRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAddR)
                    .addComponent(buttonCancelR))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listR.setModel(new DefaultListModel<String>() {

            public int getSize() { return _rListNames.size(); }
            public String getElementAt(int i) { return _rListNames.get(i); }
            public void addElement(String f) { super.addElement(f); 
                _rListNames.add(f); }
            public void add(int i, String f) { super.add(i, f); 
                _rListNames.add(i, f); }

        });
        listR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listRMouseClicked(evt);
            }
        });
        listR.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listRValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listR);

        lblHeader.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblHeader.setText("RESTAURAAAAAANTS");

        txtD.setEditable(false);
        txtD.setColumns(20);
        txtD.setLineWrap(true);
        txtD.setRows(5);
        jScrollPane2.setViewportView(txtD);

        buttonAdd.setText("Add...");
        buttonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddActionPerformed(evt);
            }
        });

        buttonEdit.setText("Edit...");
        buttonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblHeader))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHeader)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))
                        .addContainerGap(26, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(buttonAdd)
                        .addGap(27, 27, 27)
                        .addComponent(buttonEdit)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rate1ActionPerformed
        
    }//GEN-LAST:event_rate1ActionPerformed

    private void rate2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rate2ActionPerformed
        
    }//GEN-LAST:event_rate2ActionPerformed

    private void buttonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddActionPerformed
        dialogR.setVisible(true);
        buttonAddR.setText("Add");
    }//GEN-LAST:event_buttonAddActionPerformed

    private void buttonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditActionPerformed
        dialogR.setVisible(true);
        buttonAddR.setText("Edit");
        try{
            String currR = _rListNames.get(listR.getSelectedIndex());
            File f = new File("C:\\Users\\Justin\\Documents\\GitHub\\CS372\\PR4_1\\" + currR + ".txt");
            curr_restaurant.readFromFile(f);
            txtName.setText(curr_restaurant.getName());
            txtLocation.setText(curr_restaurant.getLocation());
            txtDescription.setText(curr_restaurant.getDescription());
            switch (curr_restaurant.getStarCount()){
                case 1:
                    rate1.setSelected(true);
                    break;
                case 2:
                    rate2.setSelected(true);
                    break;
                case 3:
                    rate3.setSelected(true);
                    break;
                case 4:
                    rate4.setSelected(true);
                    break;
                case 5:
                    rate5.setSelected(true);
                    break;
                default:
            }
        }
        catch(Exception e){}
    }//GEN-LAST:event_buttonEditActionPerformed

    private void buttonAddRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddRActionPerformed
        try{
            makeReview();
            curr_restaurant.writeToFile();
            ((DefaultListModel)listR.getModel()).addElement(curr_restaurant.getFileName());
            try (BufferedWriter out = new BufferedWriter(new FileWriter(file, true))) {
                out.write(curr_restaurant.getFileName());
                out.newLine();
                out.flush();
                out.close();
            }
            resetFields();
            dialogR.setVisible(false);
        }
        catch(Exception e){System.out.println("OH NOOOOO");}
    }//GEN-LAST:event_buttonAddRActionPerformed
    private void makeReview()throws Exception{
        String name = txtName.getText();
        String location = txtLocation.getText();
        String description = txtDescription.getText();
        int stars;
        if (rate1.isSelected())
            stars = 1;
        else if (rate2.isSelected())
            stars = 2;
        else if (rate3.isSelected())
            stars = 3;
        else if (rate4.isSelected())
            stars = 4;
        else if (rate5.isSelected())
            stars = 5;
        else
            throw new Exception();
        curr_restaurant = new Restaurant(name, location, description, stars);
    }
    private void resetFields(){
        txtName.setText(null);
        txtLocation.setText(null);
        txtDescription.setText(null);
    }
    private void buttonCancelRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelRActionPerformed
        dialogR.setVisible(false);
        resetFields();
    }//GEN-LAST:event_buttonCancelRActionPerformed

    private void listRValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listRValueChanged
        String currR = _rListNames.get(listR.getSelectedIndex());
        File f = new File("C:\\Users\\Justin\\Documents\\GitHub\\CS372\\PR4_1\\" + currR + ".txt");
        String line;
        String format = "";
        try{
            BufferedReader in = new BufferedReader(new FileReader(f));
            while ((line = in.readLine()) != null)
                format += (line + '\n');
                
            in.close();
            txtD.setText(format);
        }
        catch(Exception e){}
    }//GEN-LAST:event_listRValueChanged

    private void listRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listRMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_listRMouseClicked

    private void rate3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rate3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rate3ActionPerformed

    private void rate4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rate4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rate4ActionPerformed

    private void rate5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rate5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rate5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RestaurantGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RestaurantGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RestaurantGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RestaurantGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RestaurantGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdd;
    private javax.swing.JButton buttonAddR;
    private javax.swing.JButton buttonCancelR;
    private javax.swing.JButton buttonEdit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JDialog dialogR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JList listR;
    private javax.swing.JRadioButton rate1;
    private javax.swing.JRadioButton rate2;
    private javax.swing.JRadioButton rate3;
    private javax.swing.JRadioButton rate4;
    private javax.swing.JRadioButton rate5;
    private javax.swing.JTextArea txtD;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
